# Rename this file to languages.toml to enable multilingual support


[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Calacaly's Blog"
weight = 1
contentDir = "content/zh-cn"

[en]
languageName = "English"
languagedirection = "ltr"
title = "Calacaly's Blog"
weight = 2
contentDir = "content/en"
